name: Auto Update M3U Playlist

on:
  schedule:
    - cron: "0 0 * * *"  # हर 24 घंटे में अपडेट होगा (रात 12 बजे)
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Latest M3U
        run: curl -o playlist.m3u https://spoo.me/AllIN1OK

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Auto-updated M3U playlist"
          git push
